items:
  - generate_name: ''
    id: AST_LAYOUT_ATTRIBUTE_TYPE_ERROR
  - generate_name: group
    id: AST_LAYOUT_ATTRIBUTE_TYPE_GROUP
    reserved_values: ''
    type: AST_LAYOUY_ATTRIBUTE_FILTER_STRING
    text:
      en:
        - group
      fa:
        - گروه
  - generate_name: class
    id: AST_LAYOUT_ATTRIBUTE_TYPE_CLASS
    reserved_values: ''
    type: AST_LAYOUY_ATTRIBUTE_FILTER_STRING
    description:
      fa: 'ویژگی کلاس جهت تنظیم نام کلاس برای یک دستور می‌باشد.'
    text:
      en:
        - class
      fa:
        - کلاس
  - generate_name: id
    id: AST_LAYOUT_ATTRIBUTE_TYPE_ID
    reserved_values: ''
    type: AST_LAYOUY_ATTRIBUTE_FILTER_STRING
    description:
      fa: 'ویژگی شناسه جهت تنظیم شناسه برای یک دستور می‌باشد.'
    text:
      en:
        - id
      fa:
        - شناسه
  - generate_name: content
    id: AST_LAYOUT_ATTRIBUTE_TYPE_CONTENT
    reserved_values: ''
    type: AST_LAYOUY_ATTRIBUTE_FILTER_STRING
    description:
      fa: 'جهت تنظیم یک محتوا به یک دستور می‌باشد.'
    text:
      en:
        - content
      fa:
        - محتوا
  - generate_name: src
    id: AST_LAYOUT_ATTRIBUTE_TYPE_SRC
    reserved_values: ''
    type: AST_LAYOUY_ATTRIBUTE_FILTER_STRING
    text:
      en:
        - src
      fa:
        - منبع
  - generate_name: label
    id: AST_LAYOUT_ATTRIBUTE_TYPE_LABEL
    reserved_values: ''
    type: AST_LAYOUY_ATTRIBUTE_FILTER_STRING
    text:
      en:
        - label
      fa:
        - برچسب
  - generate_name: repeat
    id: AST_LAYOUT_ATTRIBUTE_TYPE_REPEAT
    reserved_values: ''
    type: AST_LAYOUY_ATTRIBUTE_FILTER_NUMBER
    text:
      en:
        - repeat
      fa:
        - تکرار
  - generate_name: dir
    id: AST_LAYOUT_ATTRIBUTE_TYPE_DIR
    reserved_values: 'ast_layout_allowed_dir'
    type: AST_LAYOUY_ATTRIBUTE_FILTER_STRING
    text:
      en:
        - dir
      fa:
        - جهت
  - generate_name: lang
    id: AST_LAYOUT_ATTRIBUTE_TYPE_LANG
    reserved_values: 'ast_layout_allowed_lang'
    type: AST_LAYOUY_ATTRIBUTE_FILTER_STRING
    text:
      en:
        - lang
      fa:
        - زبان
  - generate_name: title
    id: AST_LAYOUT_ATTRIBUTE_TYPE_TITLE
    reserved_values: ''
    type: AST_LAYOUY_ATTRIBUTE_FILTER_STRING
    text:
      en:
        - title
      fa:
        - عنوان
  - generate_name: type
    id: AST_LAYOUT_ATTRIBUTE_TYPE_TYPE
    reserved_values: 'ast_layout_allowed_form_type'
    type: AST_LAYOUY_ATTRIBUTE_FILTER_STRING
    text:
      en:
        - type
      fa:
        - نوع
  - generate_name: target
    id: AST_LAYOUT_ATTRIBUTE_TYPE_KIND
    reserved_values: 'ast_layout_allowed_form_kind'
    type: AST_LAYOUY_ATTRIBUTE_FILTER_STRING
    text:
      en:
        - kind
      fa:
        - روش
  - generate_name: author
    id: AST_LAYOUT_ATTRIBUTE_TYPE_AUTHOR
    reserved_values: ''
    type: AST_LAYOUY_ATTRIBUTE_FILTER_STRING
    text:
      en:
        - author
      fa:
        - نویسنده
  - generate_name: description
    id: AST_LAYOUT_ATTRIBUTE_TYPE_DESCRIPTION
    reserved_values: ''
    type: AST_LAYOUY_ATTRIBUTE_FILTER_STRING
    text:
      en:
        - description
      fa:
        - توضیح
  - generate_name: keywords
    id: AST_LAYOUT_ATTRIBUTE_TYPE_KEYWORDS
    reserved_values: ''
    type: AST_LAYOUY_ATTRIBUTE_FILTER_STRING
    text:
      en:
        - keywords
      fa:
        - کلمات
  - generate_name: icon
    id: AST_LAYOUT_ATTRIBUTE_TYPE_ICON
    reserved_values: ''
    type: AST_LAYOUY_ATTRIBUTE_FILTER_STRING
    text:
      en:
        - icon
      fa:
        - نمایه
  - generate_name: name
    id: AST_LAYOUT_ATTRIBUTE_TYPE_NAME
    reserved_values: ''
    type: AST_LAYOUY_ATTRIBUTE_FILTER_STRING
    text:
      en:
        - name
      fa:
        - نام
  - generate_name: charset
    id: AST_LAYOUT_ATTRIBUTE_TYPE_CHARSET
    reserved_values: 'ast_layout_allowed_charset'
    type: AST_LAYOUY_ATTRIBUTE_FILTER_STRING
    text:
      en:
        - charset
      fa:
        - فرمت متنی
  - generate_name: refresh
    id: AST_LAYOUT_ATTRIBUTE_TYPE_REFRESH
    reserved_values: ''
    type: AST_LAYOUY_ATTRIBUTE_FILTER_STRING
    text:
      en:
        - refresh
      fa:
        - بروزرسانی
  - generate_name: viewport
    id: AST_LAYOUT_ATTRIBUTE_TYPE_VIEWPORT
    reserved_values: ''
    type: AST_LAYOUY_ATTRIBUTE_FILTER_STRING
    text:
      en:
        - viewport
      fa:
        - محدوده نمایش
  - generate_name: value
    id: AST_LAYOUT_ATTRIBUTE_TYPE_VALUE
    reserved_values: ''
    type: AST_LAYOUY_ATTRIBUTE_FILTER_STRING
    text:
      en:
        - value
      fa:
        - مقدار
  - generate_name: for
    id: AST_LAYOUT_ATTRIBUTE_TYPE_FOR
    reserved_values: ''
    type: AST_LAYOUY_ATTRIBUTE_FILTER_STRING
    text:
      en:
        - for
      fa:
        - برای
  - generate_name: placeholder
    id: AST_LAYOUT_ATTRIBUTE_TYPE_PLACEHOLDER
    reserved_values: ''
    type: AST_LAYOUY_ATTRIBUTE_FILTER_STRING
    text:
      en:
        - placeholder
      fa:
        - راهنما
  - generate_name: required
    id: AST_LAYOUT_ATTRIBUTE_TYPE_REQUIRED
    reserved_values: ''
    type: AST_LAYOUY_ATTRIBUTE_FILTER_BOOL
    text:
      en:
        - required
      fa:
        - اجباری
  - generate_name: media-max-width
    id: AST_LAYOUT_ATTRIBUTE_TYPE_RESPONSIVE_MAX_WIDTH
    reserved_values: ''
    type: AST_LAYOUY_ATTRIBUTE_FILTER_NUMBER
    text:
      en:
        - media-max-width
      fa:
        - شرط حداکثر عرض
  - generate_name: media-max-height
    id: AST_LAYOUT_ATTRIBUTE_TYPE_RESPONSIVE_MAX_HEIGHT
    reserved_values: ''
    type: AST_LAYOUY_ATTRIBUTE_FILTER_NUMBER
    text:
      en:
        - media-max-height
      fa:
        - شرط حداکثر ارتفاع
  - generate_name: media-min-width
    id: AST_LAYOUT_ATTRIBUTE_TYPE_RESPONSIVE_MIN_WIDTH
    text:
      en:
        - media-min-width
      fa:
        - شرط حداقل عرض
  - generate_name: media-min-height
    id: AST_LAYOUT_ATTRIBUTE_TYPE_RESPONSIVE_MIN_HEIGHT
    text:
      en:
        - media-min-height
      fa:
        - شرط حداقل ارتفاع
