items:
  - childrens:
      - generate_name: ltr
        text:
          en:
            - ltr
          fa:
            - چپ به راست
            - چپ راست
      - generate_name: rtl
        text:
          en:
            - rtl
          fa:
            - راست به چپ
            - راست چپ
    id: ast_layout_allowed_dir
  - childrens:
      - generate_name: get
        text:
          en:
            - get
            - GET
          fa:
            - گت
      - generate_name: post
        text:
          en:
            - post
            - POST
          fa:
            - پست
    id: ast_layout_allowed_form_type
  - childrens:
      - generate_name: _blank
        text:
          en:
            - blank
            - BLANK
          fa:
            - خالی
      - generate_name: _self
        text:
          en:
            - self
            - SELF
          fa:
            - خود
      - generate_name: _parent
        text:
          en:
            - parent
            - PARENT
          fa:
            - والد
      - generate_name: _top
        text:
          en:
            - top
            - TOP
          fa:
            - بالا
    id: ast_layout_allowed_form_kind
  - childrens:
      - generate_name: UTF-8
        text:
          en:
            - utf-8
            - UTF-8
            - utf8
            - UTF8
            - utf
            - UTF
          fa:
            - یوتی‌اف
            - یوتی‌اف8
            - یوتی‌اف 8
    id: ast_layout_allowed_charset
  - childrens:
      - generate_name: fa
        text:
          en:
            - en
          fa:
            - انگلیسی
      - generate_name: fa
        text:
          en:
            - fa
          fa:
            - فارسی
    id: ast_layout_allowed_lang
