items:
  - id: AST_LAYOUT_TYPE_PARAGRAPH_RAW
    text:
      en: content
      fa: محتوا
    is_mother: false
  - id: AST_LAYOUT_TYPE_ERROR
    text:
      en: error
      fa: خطا
    is_mother: false
  - id: AST_LAYOUT_TYPE_NONE
    text:
      en: layout
      fa: صفحه
    is_mother: false
  - id: AST_LAYOUT_TYPE_PARAGRAPH
    generate_name: p
    text:
      en: paragraph
      fa: پاراگراف
    is_mother: false
  - id: AST_LAYOUT_TYPE_BUTTON
    generate_name: button
    text:
      en: button
      fa: دکمه
    is_mother: true
  - id: AST_LAYOUT_TYPE_TEXTAREA
    generate_name: textarea
    text:
      en: textarea
      fa:
        - ویرایشگرمتن
        - ویرایشگر متن
    is_mother: false
  - id: AST_LAYOUT_TYPE_LABEL
    generate_name: label
    text:
      en: label
      fa: برچسب
    is_mother: false
  - id: AST_LAYOUT_TYPE_SELECT
    generate_name: select
    text:
      en: select
      fa: فهرست کشویی
    is_mother: false
  - id: AST_LAYOUT_TYPE_FIELDSET
    generate_name: fieldset
    text:
      en: fieldset
      fa:
        - گروه‌بندی
        - گروه بندی
    is_mother: false
  - id: AST_LAYOUT_TYPE_LEGEND
    generate_name: legend
    text:
      en: legend
      fa: عنوان گروه
    is_mother: false
  - id: AST_LAYOUT_TYPE_FORM
    generate_name: form
    text:
      en: form
      fa: فرم
    is_mother: false
  - id: AST_LAYOUT_TYPE_OPTGROUP
    generate_name: optgroup
    text:
      en: optgroup
      fa: گروه انتخاب
    is_mother: false
  - id: AST_LAYOUT_TYPE_DATALIST
    generate_name: datalist
    text:
      en: datalist
      fa: داده فهرست
    is_mother: false
  - id: AST_LAYOUT_TYPE_OUTPUT
    generate_name: output
    text:
      en: output
      fa: خروجی
    is_mother: false
  - id: AST_LAYOUT_TYPE_KEYGEN
    generate_name: keygen
    text:
      en: keygen
      fa: تولید کلید
    is_mother: false
  - id: AST_LAYOUT_TYPE_SPAN
    generate_name: span
    text:
      en: span
      fa: قطعه
    is_mother: false
  - id: AST_LAYOUT_TYPE_STRONG
    generate_name: strong
    text:
      en: strong
      fa: ضخیم مهم
    is_mother: false
  - id: AST_LAYOUT_TYPE_EM
    generate_name: em
    text:
      en: em
      fa: ایتالیک پیشرفته
    is_mother: false
  - id: AST_LAYOUT_TYPE_ITALIC
    generate_name: i
    text:
      en: italic
      fa: ایتالیک
    is_mother: false
  - id: AST_LAYOUT_TYPE_BOLD
    generate_name: b
    text:
      en: bold
      fa: ضخیم
    is_mother: false
  - id: AST_LAYOUT_TYPE_SUBTITLE
    generate_name: subtitle
    text:
      en: subtitle
      fa:
        - سرتیتر
        - سر تیتر
    is_mother: false
  - id: AST_LAYOUT_TYPE_UNDERLINE
    generate_name: u
    text:
      en: underline
      fa:
        - زیرخط
        - زیر خط
    is_mother: false
  - id: AST_LAYOUT_TYPE_SMALL
    generate_name: small
    text:
      en: small
      fa: کوچک
    is_mother: false
  - id: AST_LAYOUT_TYPE_BIG
    generate_name: big
    text:
      en: big
      fa: بزرگ
    is_mother: false
  - id: AST_LAYOUT_TYPE_SUB
    generate_name: sub
    text:
      en: sub
      fa: زیرین
    is_mother: false
  - id: AST_LAYOUT_TYPE_SUP
    generate_name: sup
    text:
      en: sup
      fa: رویین
    is_mother: false
  - id: AST_LAYOUT_TYPE_S
    generate_name: s
    text:
      en: s
      fa: خط خورده
    is_mother: false
  - id: AST_LAYOUT_TYPE_MARK
    generate_name: mark
    text:
      en: mark
      fa:
        - علامتگذاری
        - علامت گذاری
    is_mother: false
  - id: AST_LAYOUT_TYPE_Q
    generate_name: q
    text:
      en: q
      fa:
        - نقل قول
        - نقل‌قول
    is_mother: false
  - id: AST_LAYOUT_TYPE_CITE
    generate_name: cite
    text:
      en: cite
      fa:
        - اثر
        - ارجاع
    is_mother: false
  - id: AST_LAYOUT_TYPE_DFN
    generate_name: dfn
    text:
      en: dfn
      fa: اصطلاح
    is_mother: false
  - id: AST_LAYOUT_TYPE_ABBR
    generate_name: abbr
    text:
      en: abbr
      fa: اختصار
    is_mother: false
  - id: AST_LAYOUT_TYPE_KBD
    generate_name: kbd
    text:
      en: kbd
      fa:
        - ورودی صفحه نمایش
        - ورودی کیبورد
    is_mother: false
  - id: AST_LAYOUT_TYPE_SAMP
    generate_name: samp
    text:
      en: samp
      fa: نمونه
    is_mother: false
  - id: AST_LAYOUT_TYPE_VAR
    generate_name: var
    text:
      en: var
      fa: متغیر
    is_mother: false
  - id: AST_LAYOUT_TYPE_RUBY
    generate_name: ruby
    text:
      en: ruby
      fa: روبین
    is_mother: false
  - id: AST_LAYOUT_TYPE_RT
    generate_name: rt
    text:
      en: rt
      fa: متن روبین
    is_mother: false
  - id: AST_LAYOUT_TYPE_RP
    generate_name: rp
    text:
      en: rp
      fa: جایگزین روبین
    is_mother: false
  - id: AST_LAYOUT_TYPE_BDI
    generate_name: bdi
    text:
      en: bdi
      fa: جداگانه
    is_mother: false
  - id: AST_LAYOUT_TYPE_BDO
    generate_name: bdo
    text:
      en: bdo
      fa: جهت دهی
    is_mother: false
  - id: AST_LAYOUT_TYPE_WBR
    generate_name: wbr
    text:
      en: wbr
      fa: شکستن کلمه
    is_mother: false
  - id: AST_LAYOUT_TYPE_HEADER
    generate_name: header
    text:
      en: header
      fa:
        - سربخش
        - سر بخش
    is_mother: false
  - id: AST_LAYOUT_TYPE_FOOTER
    generate_name: footer
    text:
      en: footer
      fa:
        - پاصفحه
        - پا صفحه
    is_mother: false
  - id: AST_LAYOUT_TYPE_NAV
    generate_name: nav
    text:
      en: nav
      fa: ناوبری
    is_mother: false
  - id: AST_LAYOUT_TYPE_SECTION
    generate_name: section
    text:
      en: section
      fa: بخش
    is_mother: false
  - id: AST_LAYOUT_TYPE_ARTICLE
    generate_name: article
    text:
      en: article
      fa: مقاله
    is_mother: false
  - id: AST_LAYOUT_TYPE_ASIDE
    generate_name: aside
    text:
      en: aside
      fa:
        - جداگانه
        - جدا گانه
    is_mother: false
  - id: AST_LAYOUT_TYPE_MAIN
    generate_name: main
    text:
      en: main
      fa: اصلی
    is_mother: false
  - id: AST_LAYOUT_TYPE_HGROUP
    generate_name: hgroup
    text:
      en: hgroup
      fa:
        - گروه سربخش
        - گروه‌سربخش
        - گروه‌سر بخش
        - گروه سر بخش
    is_mother: false
  - id: AST_LAYOUT_TYPE_FIGURE
    generate_name: figure
    text:
      en: figure
      fa: شکل
    is_mother: false
  - id: AST_LAYOUT_TYPE_FIGCAPTION
    generate_name: figcaption
    text:
      en: figcaption
      fa: زیرنویس شکل
  - id: AST_LAYOUT_TYPE_FIGCAPTION
    generate_name: figcaption
    text:
      en: figcaption
      fa: زیر نویس شکل
  - id: AST_LAYOUT_TYPE_VIDEO
    generate_name: video
    text:
      en: video
      fa: فیلم
  - id: AST_LAYOUT_TYPE_AUDIO
    generate_name: audio
    text:
      en: audio
      fa: صدا
  - id: AST_LAYOUT_TYPE_IFRAME
    generate_name: iframe
    text:
      en: iframe
      fa: سایت
  - id: AST_LAYOUT_TYPE_CANVAS
    generate_name: canvas
    text:
      en: canvas
      fa: گرافیکی
  - id: AST_LAYOUT_TYPE_DETAILS
    generate_name: details
    text:
      en: details
      fa: جزئیات
  - id: AST_LAYOUT_TYPE_DETAILS
    generate_name: details
    text:
      en: details
      fa: جزییات
  - id: AST_LAYOUT_TYPE_SUMMARY
    generate_name: summary
    text:
      en: summary
      fa: خلاصه
  - id: AST_LAYOUT_TYPE_DIALOG
    generate_name: dialog
    text:
      en: dialog
      fa: دیالوگ
  - id: AST_LAYOUT_TYPE_MENU
    generate_name: menu
    text:
      en: menu
      fa: منو
  - id: AST_LAYOUT_TYPE_MENUITEM
    generate_name: menuitem
    text:
      en: menuitem
      fa: آیتم منو
  - id: AST_LAYOUT_TYPE_MENUITEM
    generate_name: menuitem
    text:
      en: menuitem
      fa: مورد منو
  - id: AST_LAYOUT_TYPE_COMMAND
    generate_name: command
    text:
      en: command
      fa: فرمان
  - id: AST_LAYOUT_TYPE_UL
    generate_name: ul
    text:
      en: ul
      fa: فهرست غیرمرتب
  - id: AST_LAYOUT_TYPE_UL
    generate_name: ul
    text:
      en: ul
      fa: فهرست غیر مرتب
  - id: AST_LAYOUT_TYPE_OL
    generate_name: ol
    text:
      en: ol
      fa: فهرست مرتب
  - id: AST_LAYOUT_TYPE_LI
    generate_name: li
    text:
      en: li
      fa: مورد
  - id: AST_LAYOUT_TYPE_TABLE
    generate_name: table
    text:
      en: table
      fa: جدول
  - id: AST_LAYOUT_TYPE_TABLE_HEADER
    generate_name: thead
    text:
      en: table-header
      fa: سرجدول
  - id: AST_LAYOUT_TYPE_TABLE_HEADER
    generate_name: thead
    text:
      en: table-header
      fa: سر جدول
  - id: AST_LAYOUT_TYPE_TABLE_BODY
    generate_name: tbody
    text:
      en: table-body
      fa: بدنه جدول
  - id: AST_LAYOUT_TYPE_TABLE_FOOTER
    generate_name: tfoot
    text:
      en: table-footer
      fa: پاصفحه جدول
  - id: AST_LAYOUT_TYPE_TABLE_FOOTER
    generate_name: tfoot
    text:
      en: table-footer
      fa: پا صفحه جدول
  - id: AST_LAYOUT_TYPE_TABLE_TR
    generate_name: tr
    text:
      en: table-tr
      fa: ردیف
  - id: AST_LAYOUT_TYPE_TABLE_TD
    generate_name: td
    text:
      en: table-td
      fa: سلول
  - id: AST_LAYOUT_TYPE_TABLE_TH
    generate_name: th
    text:
      en: table-th
      fa: سرسلول
  - id: AST_LAYOUT_TYPE_TABLE_TH
    generate_name: th
    text:
      en: th
      fa: سر سلول
  - id: AST_LAYOUT_TYPE_CAPTION
    generate_name: caption
    text:
      en: caption
      fa: عنوان جدول
  - id: AST_LAYOUT_TYPE_COL
    generate_name: th
    text:
      en: col
      fa: ستون
  - id: AST_LAYOUT_TYPE_COLGROUP
    generate_name: colgroup
    text:
      en: colgroup
      fa:
        - گروه ستون‌ ها
        - گروه ستون‌ها
  - id: AST_LAYOUT_TYPE_INCLUDE
    generate_name: include
    text:
      en: include
      fa: فراخوانی
    is_mother: true
  - id: AST_LAYOUT_TYPE_BR
    generate_name: br
    text:
      en: br
      fa: خط بعدی
    is_mother: true
  - id: AST_LAYOUT_TYPE_HR
    generate_name: hr
    text:
      en: hr
      fa: خط
    is_mother: true
  - id: AST_LAYOUT_TYPE_INPUT
    generate_name: input
    text:
      en: input
      fa: ورودی
    is_mother: true
  - id: AST_LAYOUT_TYPE_IMG
    generate_name: img
    text:
      en: img
      fa: تصویر
    is_mother: true
  - id: AST_LAYOUT_TYPE_FONT
    generate_name: font
    text:
      en: font
      fa: قلم
    is_mother: true
  - id: AST_LAYOUT_TYPE_MEDIA
    generate_name: '@media'
    text:
      en: responsive
      fa:
        - واکنش گرا
        - واکنش‌گرا
    is_mother: true
