items:
  - id: AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_ERROR
  - id: AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_GLOBAL
    generate_name: '*'
    text:
      en: global
      fa: سراسری
  - id: AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_HOVER
    generate_name: hover
    text:
      en: hover
      fa: هاور
  - id: AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_ACTIVE
    generate_name: active
    text:
      en: active
      fa: فعال
  - id: AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_FOCUS
    generate_name: focus
    text:
      en: focus
      fa: فوكوس
  - id: AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_VISITED
    generate_name: visited
    text:
      en: visited
      fa: بازديد
  - id: AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_LINK
    generate_name: link
    text:
      en: link
      fa: لينك
  - id: AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_FOCUS_VISIBLE
    generate_name: focus-visible
    text:
      en: focus-visible
      fa: فوكوس قابل مشاهده
  - id: AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_FOCUS_WITHIN
    generate_name: focus-within
    text:
      en: focus-within
      fa: فوكوس داخلي
  - id: AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_CHECKED
    generate_name: checked
    text:
      en: checked
      fa: انتخاب
  - id: AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_DISABLED
    generate_name: disabled
    text:
      en: disabled
      fa: غيرفعال
  - id: AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_ENABLED
    generate_name: enabled
    text:
      en: enabled
      fa: فعال
  - id: AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_ENABLED
    generate_name: enabled
    text:
      en: enabled
      fa: فعال
  - id: AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_REQUIRED
    generate_name: required
    text:
      en: required
      fa: ضروري
  - id: AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_OPTIONAL
    generate_name: optional
    text:
      en: optional
      fa: اختياري
  - id: AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_READ_ONLY
    generate_name: read-only
    text:
      en: read-only
      fa: فقط خواندني
  - id: AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_READ_WRITE
    generate_name: read-write
    text:
      en: read-write
      fa: قابل نوشتن
  - id: AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_VALID
    generate_name: valid
    text:
      en: valid
      fa: معتبر
  - id: AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_INVALID
    generate_name: invalid
    text:
      en: invalid
      fa: نامعتبر
  - id: AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_IN_RANGE
    generate_name: in-range
    text:
      en: in-range
      fa: در محدوده
  - id: AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_OUT_OF_RANGE
    generate_name: out-of-range
    text:
      en: out-of-range
      fa: خارج از محدوده
  - id: AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_PLACEHOLDER_SHOWN
    generate_name: placeholder-shown
    text:
      en: placeholder-shown
      fa: نمايش جايگير
  - id: AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_BLANK
    generate_name: blank
    text:
      en: blank
      fa: خالي
  - id: AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_TARGET
    generate_name: target
    text:
      en: target
      fa: هدف
  - id: AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_ROOT
    generate_name: root
    text:
      en: root
      fa: ريشه
  - id: AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_NTH_CHILD
    generate_name: nth-child
    text:
      en: nth-child
      fa: فرزند nام
  - id: AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_NTH_LAST_CHILD
    generate_name: nth-last-child
    text:
      en: nth-last-child
      fa: آخرين فرزند nام
  - id: AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_NTH_OF_TYPE
    generate_name: nth-of-type
    text:
      en: nth-of-type
      fa: نوع nام
  - id: AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_NTH_LAST_OF_TYPE
    generate_name: nth-last-of-type
    text:
      en: nth-last-of-type
      fa: آخرين نوع nام
  - id: AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_FIRST_CHILD
    generate_name: first-child
    text:
      en: first-child
      fa: اولين فرزند
  - id: AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_LAST_CHILD
    generate_name: last-child
    text:
      en: last-child
      fa: آخرين فرزند
  - id: AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_FIRST_OF_TYPE
    generate_name: first-of-type
    text:
      en: first-of-type
      fa: اولين نوع
  - id: AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_LAST_OF_TYPE
    generate_name: last-of-type
    text:
      en: last-of-type
      fa: آخرين نوع
  - id: AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_ONLY_CHILD
    generate_name: only-child
    text:
      en: only-child
      fa: تنها فرزند
  - id: AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_ONLY_OF_TYPE
    generate_name: only-of-type
    text:
      en: only-of-type
      fa: تنها نوع
  - id: AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_EMPTY
    generate_name: empty
    text:
      en: empty
      fa: خالي
