- items:
    generate_name]: ''
    id]: AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_ERROR
    text]:
      en]: global
      fa]: سراسری
- items:
    generate_name]: '*'
    id]: AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_GLOBAL
    text]:
      en]: hover
      fa]: هاور
- items:
    generate_name]: hover
    id]: AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_HOVER
    text]:
      en]: active
      fa]: فعال
- items:
    generate_name]: active
    id]: AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_ACTIVE
    text]:
      en]: focus
      fa]: فوكوس
- items:
    generate_name]: focus
    id]: AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_FOCUS
    text]:
      en]: visited
      fa]: بازديد
- items:
    generate_name]: visited
    id]: AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_VISITED
    text]:
      en]: link
      fa]: لينك
- items:
    generate_name]: link
    id]: AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_LINK
    text]:
      en]: focus-visible
      fa]: فوكوس قابل مشاهده
- items:
    generate_name]: focus-visible
    id]: AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_FOCUS_VISIBLE
    text]:
      en]: focus-within
      fa]: فوكوس داخلي
- items:
    generate_name]: focus-within
    id]: AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_FOCUS_WITHIN
    text]:
      en]: checked
      fa]: انتخاب
- items:
    generate_name]: checked
    id]: AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_CHECKED
    text]:
      en]: disabled
      fa]: غيرفعال
- items:
    generate_name]: disabled
    id]: AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_DISABLED
    text]:
      en]: enabled
      fa]: فعال
- items:
    generate_name]: enabled
    id]: AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_ENABLED
    text]:
      en]: required
      fa]: ضروري
- items:
    generate_name]: required
    id]: AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_REQUIRED
    text]:
      en]: optional
      fa]: اختياري
- items:
    generate_name]: optional
    id]: AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_OPTIONAL
    text]:
      en]: read-only
      fa]: فقط خواندني
- items:
    generate_name]: read-only
    id]: AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_READ_ONLY
    text]:
      en]: read-write
      fa]: قابل نوشتن
- items:
    generate_name]: read-write
    id]: AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_READ_WRITE
    text]:
      en]: valid
      fa]: معتبر
- items:
    generate_name]: valid
    id]: AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_VALID
    text]:
      en]: invalid
      fa]: نامعتبر
- items:
    generate_name]: invalid
    id]: AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_INVALID
    text]:
      en]: in-range
      fa]: در محدوده
- items:
    generate_name]: in-range
    id]: AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_IN_RANGE
    text]:
      en]: out-of-range
      fa]: خارج از محدوده
- items:
    generate_name]: out-of-range
    id]: AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_OUT_OF_RANGE
    text]:
      en]: placeholder-shown
      fa]: نمايش جايگير
- items:
    generate_name]: placeholder-shown
    id]: AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_PLACEHOLDER_SHOWN
    text]:
      en]: blank
      fa]: خالي
- items:
    generate_name]: blank
    id]: AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_BLANK
    text]:
      en]: target
      fa]: هدف
- items:
    generate_name]: target
    id]: AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_TARGET
    text]:
      en]: root
      fa]: ريشه
- items:
    generate_name]: root
    id]: AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_ROOT
    text]:
      en]: nth-child
      fa]: فرزند nام
- items:
    generate_name]: nth-child
    id]: AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_NTH_CHILD
    text]:
      en]: nth-last-child
      fa]: آخرين فرزند nام
- items:
    generate_name]: nth-last-child
    id]: AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_NTH_LAST_CHILD
    text]:
      en]: nth-of-type
      fa]: نوع nام
- items:
    generate_name]: nth-of-type
    id]: AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_NTH_OF_TYPE
    text]:
      en]: nth-last-of-type
      fa]: آخرين نوع nام
- items:
    generate_name]: nth-last-of-type
    id]: AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_NTH_LAST_OF_TYPE
    text]:
      en]: first-child
      fa]: اولين فرزند
- items:
    generate_name]: first-child
    id]: AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_FIRST_CHILD
    text]:
      en]: last-child
      fa]: آخرين فرزند
- items:
    generate_name]: last-child
    id]: AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_LAST_CHILD
    text]:
      en]: first-of-type
      fa]: اولين نوع
- items:
    generate_name]: first-of-type
    id]: AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_FIRST_OF_TYPE
    text]:
      en]: last-of-type
      fa]: آخرين نوع
- items:
    generate_name]: last-of-type
    id]: AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_LAST_OF_TYPE
    text]:
      en]: only-child
      fa]: تنها فرزند
- items:
    generate_name]: only-child
    id]: AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_ONLY_CHILD
    text]:
      en]: only-of-type
      fa]: تنها نوع
- items:
    generate_name]: only-of-type
    id]: AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_ONLY_OF_TYPE
    text]:
      en]: empty
      fa]: خالي
- items:
    generate_name]: empty
    id]: AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_EMPTY
